pub const ICON_TERMINAL: &str = "\u{f120}"; // fa-terminal
pub const ICON_LASER: &str = "\u{f06d}"; // fa-fire (using fire for laser)
pub const ICON_MOVE: &str = "\u{f047}"; // fa-arrows
pub const ICON_POWER: &str = "\u{f0e7}"; // fa-bolt
pub const ICON_HOME: &str = "\u{f015}"; // fa-home
pub const ICON_UNLOCK: &str = "\u{f09c}"; // fa-unlock
pub const ICON_SETTINGS: &str = "\u{f013}"; // fa-cog
pub const ICON_CHECK: &str = "\u{f058}"; // fa-check-circle
pub const ICON_ARROW_UP: &str = "\u{f062}"; // fa-arrow-up
pub const ICON_ARROW_DOWN: &str = "\u{f063}"; // fa-arrow-down
pub const ICON_ARROW_LEFT: &str = "\u{f060}"; // fa-arrow-left
pub const ICON_ARROW_RIGHT: &str = "\u{f061}"; // fa-arrow-right
pub const ICON_CROSSHAIR: &str = "\u{f05b}"; // fa-crosshairs
pub const ICON_USB: &str = "\u{f287}"; // fa-usb
pub const ICON_FLAME: &str = "\u{f06d}"; // fa-fire
pub const ICON_GAUGE: &str = "\u{f0e4}"; // fa-tachometer
pub const ICON_SHIELD: &str = "\u{f132}"; // fa-shield
pub const ICON_REFRESH: &str = "\u{f021}"; // fa-refresh
pub const ICON_CPU: &str = "\u{f2db}"; // fa-microchip
pub const ICON_TRASH: &str = "\u{f1f8}"; // fa-trash
pub const ICON_LAYERS: &str = "\u{f0c9}"; // fa-bars (or fa-layers if available)
pub const ICON_COPY: &str = "\u{f0c5}"; // fa-copy
pub const ICON_SWEEP: &str = "\u{f518}"; // fa-broom
pub const ICON_FILE: &str = "\u{f15b}"; // fa-file
pub const ICON_IMAGE: &str = "\u{f03e}"; // fa-image
pub const ICON_EYE: &str = "\u{f06e}"; // fa-eye
pub const ICON_EYE_SLASH: &str = "\u{f070}"; // fa-eye-slash
pub const ICON_SPINNER: &str = "\u{f110}"; // fa-spinner
pub const ICON_SERIAL: &str = "\u{f120}"; // fa-terminal (using same as terminal for now)
pub const ICON_SQUARE: &str = "\u{f096}"; // fa-square-o
pub const ICON_CUBE: &str = "\u{f0ec7}"; // nf-md-cube_outline or similar requested icon
pub const ICON_SQUARE_VECTOR: &str = "\u{f0001}"; // nf-mdi-vector-square
pub const ICON_FONT: &str = "\u{e659}"; // nf-seti-font
pub const ICON_STOP: &str = "\u{f03c3}"; // nf-mdi-stop-circle (or similar)
